services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: riskops-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./data:/var/opt/mssql/import:ro
      - ./sql:/sql:ro

volumes:
  mssql-data:
